source 'https://github.com/CocoaPods/Specs.git'

target 'Spark-Setup', :exclusive => true do
  pod "Spark-Setup", :path => "../"
  pod "Spark-SDK"
end

target 'Tests', :exclusive => true do
  pod "Spark-Setup", :path => "../"
  pod "Spark-SDK"

  
end
