source 'https://github.com/CocoaPods/Specs.git'

target 'Spark-Setup', :exclusive => true do
  pod "Spark-Setup", :path => "../"
  pod "Spark-SDK", :path => "../../spark-sdk-ios/"
end

target 'Tests', :exclusive => true do

end
